### ISSUE TITLE
Favicon illegible on light backgrounds

### ISSUE THREAD

**Issue by ioncorimenia** [ScruffySounds/ScruffyWebsite#1]
Since the favicon is white with a transparent background, if the user agent displays it on a white background, it is illegible. Perhaps give it a dropshadow?

![A screenshot of a tab displaying the scruffy website. Its favicon is almost invisible, since it is white on a light grey background.](https://user-images.githubusercontent.com/9449583/89667735-f00cd900-d8dc-11ea-8111-f559b3b067ec.png)

**Comment by ScruffySounds** [comment]
Dear jtvjan,

Thank you for the heads up! I've given the favicon a black circle with
white outline to make it legible.

Thanks again!
Scruffy
